### ISSUE TITLE
Karpenter Resource Helm Chart to Support SnapshotID

### ISSUE THREAD

**Issue by lindarr915** [aws-ia/terraform-aws-eks-data-addons#40]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Let the Karpenter Resource helm chart to accept snpashot ID to support developing the feature [Enhance pull speed for Large ML container Images with Bottlerocket](https://github.com/awslabs/data-on-eks/issues/559)

**Comment by lindarr915** [comment]
Reopen the issue

**Comment by askulkarni2** [comment]
Fixed in #41
